### ISSUE TITLE
Give zoning system a compelling name

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder#2]

**Comment by Robinlovelace** [comment]
Concentric Segmented Annuli (CSA) being good enough for now, safe enough to try. Any other more compelling ideas welcome!

**Comment by Robinlovelace** [comment]
The dartboard zoning system.

**Comment by Robinlovelace** [comment]
Or CLOC: Concentric rings and Linear segments for zOning Cities.

**Comment by mtennekes** [comment]
How about the **ClockBoard** zoning system.

Why? It is a mixture between clock and a dartboard. The clock itself has 12 segments, but is one-dimensional. The dartboard is two-dimensional (segments and rings), but contains 20 rather than 12 segments.

**Comment by Robinlovelace** [comment]
I like it!

**Comment by Robinlovelace** [comment]
ClockBoard it is :tada:
