### ISSUE TITLE
Error when running zb_zone

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder#23]
I get this error: 

``` r
lisbon_centrepoint = tmaptools::geocode_OSM("lisbon", as.sf = TRUE)
z = zonebuilder::zb_zone(lisbon_centrepoint, n_circles = 2)
#> Error: 'st_make_valid' is not an exported object from 'namespace:lwgeom'
```

<sup>Created on 2020-04-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Any ideas @mtennekes and sorry I've not looked at this in so long.

**Comment by mtennekes** [comment]
No worries;-) `st_make_valid` has moved from `lwgeom` to `sf`.

**Comment by Robinlovelace** [comment]
Great, thanks Martijn, fixed now.
