### ISSUE TITLE
CRAN issues

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder#27]
Please add \value to .Rd files regarding exported methods and explain
the functions results in the documentation. Please write about the
structure of the output (class) and also what the output means. (If a
function does not return a value, please document that too, e.g.
\value{No return value, called for side effects} or similar)
Missing Rd-tags:
      zb_doughnut.Rd: \value
      zb_plot.Rd: \value
      zb_segment.Rd: \value
      zb_view.Rd: \value

Please make sure that you do not change the user's options, par or
working directory. If you really have to do so within functions, please
ensure with an *immediate* call of on.exit() that the settings are reset
when the function is exited. e.g.:
...
oldpar <- par(no.readonly = TRUE)    # code line i
on.exit(par(oldpar))            # code line i + 1
...
par(mfrow=c(2,2))            # somewhere after
...
e.g.: plot.R
If you're not familiar with the function, please check ?on.exit. This
function makes it possible to restore options before exiting a function
even if the function breaks. Therefore it needs to be called immediately
after the option change within a function.

Please fix and resubmit.

**Comment by Robinlovelace** [comment]
Plan to look next week. Please take a look and let me know if you get a chance @mtennekes - almost there!

**Comment by mtennekes** [comment]
Great! Sorry, have no time myself to look at it.

**Comment by Robinlovelace** [comment]
No problem @mtennekes, according to @agila5 these are easy fixes. All the best your side!
