### ISSUE TITLE
FOSS4G abstract submission

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder#33]
Deadline 30th March: https://callforpapers.2021.foss4g.org/foss4g-2021-academic/

**Comment by Robinlovelace** [comment]
Heads-up @dabreegster and @mtennekes having looked again at the submission form I've updated the abstract. It asks for author affiliations, please double check, let me know of any improvements you spot or :+1: 

https://github.com/zonebuilders/zonebuilder/blob/master/paper/foss4g/foss4g-zonebuilder-abstract.md

Plan to submit this here by end of the day https://callforpapers.2021.foss4g.org/foss4g2021

**Comment by dabreegster** [comment]
Whoops, I meant to start a PR, but pressed buttons on github and wound up committing a small typo fix: 7b68ba7e948fa204572c921733a4b27f0af01b1b
See my comments in the description. Thanks!

**Comment by Robinlovelace** [comment]
Thanks @dabreegster great stuff, will submit now :tada:

Regarding your comment:

> I live in the 3rd ring at 4'o'clock is easier to parse, but way more verbose.

Must say I agree. I propose we shift from 3D 3 @4'o'clock, so to speak. What do you reckon @mtennekes ? Has consequences for the paper. In practice I'm skeptical that either will likely catch on among all but geo enthusiasts but we want to make it as accessible as possible and I think the 'o'clock language helps in that direction.

**Comment by Robinlovelace** [comment]
Almost there.

![image](https://user-images.githubusercontent.com/1825120/114573301-2b338900-9c70-11eb-9e87-697d7ae5379f.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/114574894-903bae80-9c71-11eb-922f-729d512160b4.png)
