### ISSUE TITLE
Submit paper

### ISSUE THREAD

**Issue by Robinlovelace** [zonebuilders/zonebuilder#39]
![tokyo](https://user-images.githubusercontent.com/1825120/127287579-837b3d85-7ffe-41fd-b695-008b6448f13b.png)

**Comment by mtennekes** [comment]
See also https://github.com/zonebuilders/zonebuilder/discussions/32

**Comment by Robinlovelace** [comment]
Good point, worth including one of those figures in the Applications section in the paper? I guess so.

**Comment by Robinlovelace** [comment]
Figure for the Applications section

![image](https://user-images.githubusercontent.com/1825120/127722483-44e1ea76-d916-4518-bdc0-b89a34600a20.png)

**Comment by Robinlovelace** [comment]
Compressed version for online vignette/package

![navigation-small](https://user-images.githubusercontent.com/1825120/127722684-e4f0f58a-44b2-48b9-8bdd-cd09bae4e250.png)

**Comment by Robinlovelace** [comment]
Larger version without clutter

![navigation](https://user-images.githubusercontent.com/1825120/127722701-36ca3674-0522-40d6-9a69-e745ca628bca.png)

**Comment by Robinlovelace** [comment]
This is what I'm thinking for the 2nd application example: showing the spatial distribution of a single variable in a city using a consistent frame of reference:

![image](https://user-images.githubusercontent.com/1825120/128056975-782a3a6c-0e8c-4dca-96c3-20f582c81095.png)

**Comment by mtennekes** [comment]
Good one! I would remove the first figure, because the clipping creates artefacts: F1, F2, G6, G9 (I love this system!) all have a darker color than in the second figure.

So I would suggest to keep the second and third figures, reverse them (so start with the classic admin choropleth). And make sure they have the same zoom scale (so the clockboard should be relatively larger). I can help you with that if needed since it is tmap related.

**Comment by Robinlovelace** [comment]
This any better? 

![image](https://user-images.githubusercontent.com/1825120/128397242-4a6bd4be-2551-404c-a86b-18555e74a4ae.png)


Not sure what's going on with the resolution, I may just use `include_graphics()` to include a high res version... See here for the source and new description https://zonebuilders.github.io/zonebuilder/articles/paper.html


Any comments and suggested changes very welcome here:

https://github.com/zonebuilders/zonebuilder/blob/545b81f8895bba37f8287ed7295b77045e3fa253/vignettes/paper.Rmd#L392-L407

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/128508694-5b5485ca-6f1b-4c21-bdb6-9269a7981dd5.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/128612926-a1f24626-10bc-479b-8f57-cd75ac6187be.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/128613018-0843bee1-6462-466a-9bd4-2166855ef4c0.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/128613050-96fd8882-10c5-47d8-af2f-90fceeba8d81.png)

**Comment by Robinlovelace** [comment]
Paper submitted and preprint available here: https://osf.io/vncgw/
